#!/usr/bin/env bash
alias ls="exa"
alias find="fd"
alias grep="rg"
alias top="btm"
# alias sed="sd" -- can't do this because sd is not compatible with sed's commands that Unix by default uses
alias htop="btm"
alias ps="procs"
alias cat="bat"
alias time="hyperfine"
alias cloc="tokei"
alias tree="br"
alias man="tldr"
alias history="atuin history list"
alias cd="z"

alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias lg="lazygit"

alias "??"="gh copilot"

alias c="clear"

alias tmux="zellij"
alias zj="zellij"

set_keyboard_layout() {
	local layout="$1"

	if [ -n "$SWAYSOCK" ]; then
		# We are in a Sway session
		swaymsg input type:keyboard xkb_layout "$layout"
	else
		# Assuming we are in an Xorg session
		setxkbmap "$layout"
	fi
}

# Alias for the function
alias asdf="set_keyboard_layout real-prog-dvorak"
alias aoeu="set_keyboard_layout us"

alias xsc="xclip -selection clipboard"
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"
alias vim="nvim"
alias python="python3"
alias dc="docker compose"
alias icat="kitty +kitten icat"
alias docker-compose="docker compose"
# alias k=kubectl
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

alias ssock="export SWAYSOCK=/run/user/$(id -u)/sway-ipc.$(id -u).$(pgrep -x sway).sock"

alias sshot='f() { grim -g "$(slurp)" - | wl-copy; unset -f f; }; f'
