#!/usr/bin/env bash
alias ls="exa"
alias find="fd"
alias grep="rg"
alias top="btm"
# alias sed="sd" -- can't do this because sd is not compatible with sed's commands that Unix by default uses
alias htop="btm"
alias ps="procs"
alias cat="bat"
alias time="hyperfine"
alias cloc="tokei"

alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias lg="lazygit"

alias c="clear"

alias tmux="zellij"
alias zj="zellij"

alias asdf="setxkbmap real-prog-dvorak"
alias aoeu="setxkbmap us"

alias xsc="xclip -selection clipboard"
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"
alias vim="$VIM"
alias python="python3"
alias dc="docker compose"
alias icat="kitty +kitten icat"
alias docker-compose="docker compose"
# alias k=kubectl
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
