keybinding:
  universal:
    return: '<c-/>'

gui: 
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline

os:
  editPreset: 'nvim-remote'
  open: 'nvim {{filename}}'
# git:
#   paging:
#     colorArg: never
#     pager: delta --dark --paging=never
