keybinding:
  universal:
    return: '<c-\>'

gui: 
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline

os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
# git:
#   paging:
#     colorArg: never
#     pager: delta --dark --paging=never
