keybinding:
  universal:
    return: '<c-l>'

gui: 
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline

os:
  editPreset: $EDITOR
  open: '$EDITOR {{filename}}'
# git:
#   paging:
#     colorArg: never
#     pager: delta --dark --paging=never
